"""empty message

Revision ID: 6b15852e09f5
Revises: 
Create Date: 2020-07-04 22:14:23.429227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b15852e09f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ACCESSID', sa.String(length=50), nullable=False),
    sa.Column('PatientID', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('labeled', sa.Boolean(), nullable=False),
    sa.Column('label_time', sa.Date(), nullable=True),
    sa.Column('has_pathology', sa.Boolean(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('upload_time', sa.Date(), nullable=True),
    sa.Column('labeler_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['labeler_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathology',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ultra_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('regulation', sa.String(length=50), nullable=True),
    sa.Column('border', sa.String(length=50), nullable=True),
    sa.Column('bloodstream', sa.String(length=50), nullable=True),
    sa.Column('part', sa.String(length=50), nullable=True),
    sa.Column('single_training', sa.String(length=50), nullable=True),
    sa.Column('single_label', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('x', sa.String(length=50), nullable=True),
    sa.Column('y', sa.String(length=50), nullable=True),
    sa.Column('width', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ultra_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ultra_report')
    op.drop_table('ultra_image')
    op.drop_table('pathology')
    op.drop_table('access')
    op.drop_table('user')
    # ### end Alembic commands ###
